# Generated by Django 3.2.14 on 2022-09-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('madplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdays',
            name='date',
            field=models.DateField(verbose_name='%d-%m-%y'),
        ),
    ]
