# Generated by Django 3.2.14 on 2022-07-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madplan', '0002_alter_weekdays_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekdays',
            name='week_day_name',
        ),
    ]
