# Generated by Django 3.2.14 on 2023-03-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('madplan', '0002_alter_weekdays_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='imege',
            field=models.ImageField(blank=True, null=True, upload_to='mealplan/images/'),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='date',
            field=models.DateField(verbose_name='%y-%m-%d'),
        ),
    ]
