# Generated by Django 3.2.14 on 2023-03-01 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('madplan', '0003_auto_20230301_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='imege',
        ),
    ]
