# Generated by Django 3.2.14 on 2023-03-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('madplan', '0004_remove_recipes_imege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
