# Generated by Django 3.2.14 on 2023-03-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('madplan', '0005_alter_ingredients_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdays',
            name='date',
            field=models.DateField(verbose_name='%d-%m-%y'),
        ),
    ]
